apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: 'gcr.io/beaming-botany-293512/eureka-server:gcp1'
          env:
            - name: PROFILE
              value: cloud
          ports:
            - containerPort: 8761

