apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deploy
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: 'gcr.io/$GOOGLE_CLOUD_PROJECT/eureka-server:gcp1'
          env:
            - name: PROFILE
              value: cloud
          ports:
            - containerPort: 8761