apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    name: eureka
spec:
  ports:
    - port: 80
      targetPort: 8761
      protocol: TCP
  selector:
    app: eureka
  type: ClusterIP